name: Execute Scripts

on:
  push:
    branches:
      - main

jobs:
  run_scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: List Files in Directory
      run: |
        echo "Listing files in the repository..."
        ls -R  # List all files recursively

    - name: Run get_utc5_time.py
      id: get_time
      run: |
        output=$(python src/get_utc5_time.py)
        echo "current_time=${output}" >> $GITHUB_ENV  # Store the output in an environment variable

    - name: Run sum_date_time_parts.py
      id: sum_parts
      run: |
        # Capture the output from the previous script
        date_time_output="${{ env.current_time }}"
        python src/sum_date_time_parts.py "$date_time_output"

    - name: Run divide_values.py
      run: |
        # Capture the output from the sum_parts script
        sum_output=$(python src/sum_date_time_parts.py "${{ env.current_time }}")
        date_sum=$(echo "$sum_output" | awk -F, '{print $1}')
        time_sum=$(echo "$sum_output" | awk -F, '{print $2}')
        python src/divide_values.py "$date_sum" "$time_sum"