name: Run Scripts

on: 
  push:
    branches:
      - main

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List files in the repository
        run: |
          echo "Listing files in the repository..."
          ls -R

      - name: Capture current UTC-5 time
        id: get_time
        run: |
          output=$(python src/get_utc5_time.py)  # Capture the output directly
          echo "output=$output" >> $GITHUB_ENV  # Store the output in an environment variable

      - name: Print captured time
        run: echo "Captured UTC-5 time: ${{ env.output }}"

      # Add steps to execute the sum_parts and divide_values scripts
      - name: Run sum_parts script
        run: |
          python src/sum_date_time_parts.py "${{ env.output }}"

      - name: Run divide_values script
        run: |
          # Replace 10 and 2 with the actual values you need
          python src/divide_values.py 10 2