name: Multi Scripts Chain Execution

on:
  push:
    branches:
      - main
      
env:
  SRC_DIRECTORY: src  # Declare SRC_DIRECTORY as a global environment variable, making the path available throughout the workflow
  
jobs:
  run_scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: List Files in Directory
      run: |
        echo "Listing files in the repository..."
        ls -R  # List all files recursively

    - name: Run get_utc5_time.py
      id: get_time
      run: |
        output=$(python "${{ env.SRC_DIRECTORY }}/get_utc5_time.py")
        echo "current_time=${output}" >> $GITHUB_ENV  # Store the output in an environment variable

    - name: Run sum_date_time_parts.py
      id: sum_parts
      # Capture the output from the previous script
      run: |
        date_time_output="${{ env.current_time }}"
        values=$(python "${{ env.SRC_DIRECTORY }}/sum_date_time_parts.py" "$date_time_output")
        echo "tuple_values=$(echo $values | tr -d '() ')" >> $GITHUB_ENV  # Store the output in an environment variable

    - name: Run divide_values.py
    # Capture the sum result from the previous step
      run: |
        sum_output="${{ env.tuple_values }}"
        date_sum=$(echo "$sum_output" | cut -d',' -f1)
        time_sum=$(echo "$sum_output" | cut -d',' -f2)
        python "${{ env.SRC_DIRECTORY }}/divide_values.py" $date_sum $time_sum
