name: Execute Scripts

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering if needed

jobs:
  run_scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Run get_current_time.py
      id: get_time
      run: |
        python src/get_current_time.py

    - name: Run sum_date_time_parts.py
      id: sum_parts
      run: |
        # Capture the output from the previous script
        date_time_output=$(python src/get_current_time.py)
        python src/sum_date_time_parts.py "$date_time_output"

    - name: Run divide_values.py
      run: |
        # Capture the output from the sum_parts script
        sum_output=$(python src/sum_date_time_parts.py "$date_time_output")
        date_sum=$(echo "$sum_output" | awk -F, '{print $1}')
        time_sum=$(echo "$sum_output" | awk -F, '{print $2}')
        python src/divide_values.py "$date_sum" "$time_sum"