name: Execute Scripts

on:
  push:
    branches:
      - main

jobs:
  run_scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List Files in Directory
        run: |
          echo "Listing files in the repository..."
          ls -R  # List all files recursively

      - name: Run get_utc5_time.py
        id: get_time
        run: |
          output=$(python src/get_utc5_time.py)
          echo "current_time=${output}" >> $GITHUB_ENV  # Store the output in an environment variable
              
      - name: Run sum_date_time_parts.py
        id: sum_parts
        run: |
          # Captura la salida del script y sepárala
          date_time_output="${{ env.current_time }}"
          sum_result=$(python src/sum_date_time_parts.py "$date_time_output")
          echo "sum_result=${sum_result}"
          date_sum=$(echo "$sum_result" | cut -d',' -f1)  # Separar la primera parte
          time_sum=$(echo "$sum_result" | cut -d',' -f2)  # Separar la segunda parte
          
          # Guardar las variables en el entorno
          echo "date_sum=${date_sum}" >> $GITHUB_ENV
          echo "time_sum=${time_sum}" >> $GITHUB_ENV

      - name: Run divide_values.py
        run: |
          # Captura las variables de entorno previamente guardadas
          python src/divide_values.py "${{ env.date_sum }}" "${{ env.time_sum }}"